In [1]:
import glob
from scipy import signal
import pandas as pd
import scipy.io
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline

## Import Potential Data

#### The raw voltage data is stored in .mat files, one for each channel of the electrode. Load these into a 16 x n DataFrame, where n is the number of samples.

In [2]:
files = glob.glob('data/data/*B.mat')
files = sorted(files)

In [3]:
files

['data/data/CSC01B.mat',
 'data/data/CSC02B.mat',
 'data/data/CSC03B.mat',
 'data/data/CSC04B.mat',
 'data/data/CSC05B.mat',
 'data/data/CSC06B.mat',
 'data/data/CSC07B.mat',
 'data/data/CSC08B.mat',
 'data/data/CSC09B.mat',
 'data/data/CSC10B.mat',
 'data/data/CSC11B.mat',
 'data/data/CSC12B.mat',
 'data/data/CSC13B.mat',
 'data/data/CSC14B.mat',
 'data/data/CSC15B.mat',
 'data/data/CSC16B.mat']

In [4]:
ch = len(files)
potential = []
for i in range(0, ch): 
    print('Loading file ' + str(i+1) + ' of ' + str(ch))
    data = scipy.io.loadmat(files[i])
    data = data['data']
    s = data.shape
    data = np.reshape(data, (1, s[0]))
    potential.append(data)

Loading file 1 of 16
Loading file 2 of 16
Loading file 3 of 16
Loading file 4 of 16
Loading file 5 of 16
Loading file 6 of 16
Loading file 7 of 16
Loading file 8 of 16
Loading file 9 of 16
Loading file 10 of 16
Loading file 11 of 16
Loading file 12 of 16
Loading file 13 of 16
Loading file 14 of 16
Loading file 15 of 16
Loading file 16 of 16


In [5]:
potential

[array([[-0.01013184, -0.03005981, -0.04089355, ..., -0.00524902,
         -0.02633667, -0.03570557]]),
 array([[ 0.01077271, -0.0015564 , -0.01379395, ..., -0.01004028,
         -0.01373291, -0.01641846]]),
 array([[ 0.0010376 ,  0.00192261,  0.00082397, ..., -0.00457764,
         -0.00546265, -0.00366211]]),
 array([[ 0.01831055,  0.00878906, -0.00131226, ..., -0.04025269,
         -0.05142212, -0.04718018]]),
 array([[ 0.00430298, -0.00137329, -0.00738525, ..., -0.00280762,
         -0.01287842, -0.02011108]]),
 array([[-0.0135498 , -0.02246094, -0.02633667, ..., -0.01800537,
         -0.02984619, -0.02941895]]),
 array([[-0.00183105, -0.01425171, -0.0196228 , ..., -0.00289917,
         -0.02166748, -0.0328064 ]]),
 array([[ 0.00738525, -0.0128479 , -0.02536011, ...,  0.00201416,
         -0.0171814 , -0.03018188]]),
 array([[ 0.0284729 ,  0.01144409, -0.00704956, ..., -0.02420044,
         -0.0324707 , -0.03018188]]),
 array([[ 0.01434326,  0.00463867, -0.00415039, ..., -0.00900269

#### Formatting for converstion from matrix to Pandas DataFrame.

In [5]:
potential = np.transpose(potential)
potential = np.squeeze(potential)
potential

array([[-1.01318359e-02,  1.07727051e-02,  1.03759766e-03, ...,
         2.38037109e-03, -5.16052246e-02, -1.66015625e-02],
       [-3.00598145e-02, -1.55639648e-03,  1.92260742e-03, ...,
        -2.65502930e-03, -4.17785645e-02, -1.32751465e-02],
       [-4.08935547e-02, -1.37939453e-02,  8.23974609e-04, ...,
        -1.31225586e-03, -1.34582520e-02, -1.36718750e-02],
       ...,
       [-5.24902344e-03, -1.00402832e-02, -4.57763672e-03, ...,
         3.32946777e-02, -9.15527344e-05,  5.91735840e-02],
       [-2.63366699e-02, -1.37329102e-02, -5.46264648e-03, ...,
         1.44958496e-02, -2.35900879e-02,  4.13818359e-02],
       [-3.57055664e-02, -1.64184570e-02, -3.66210938e-03, ...,
         4.27246094e-04, -3.04870605e-02,  1.98364258e-02]])

In [6]:
col_labels = []
for i in range(0, ch): 
    l = 'Ch' + str(i + 1)
    col_labels.append(l)

In [7]:
col_labels

['Ch1',
 'Ch2',
 'Ch3',
 'Ch4',
 'Ch5',
 'Ch6',
 'Ch7',
 'Ch8',
 'Ch9',
 'Ch10',
 'Ch11',
 'Ch12',
 'Ch13',
 'Ch14',
 'Ch15',
 'Ch16']

In [8]:
potential_df = pd.DataFrame(potential, columns = col_labels)

In [9]:
potential_df.head()

Ch1       Ch2       Ch3       Ch4       Ch5       Ch6       Ch7  \
0 -0.010132  0.010773  0.001038  0.018311  0.004303 -0.013550 -0.001831   
1 -0.030060 -0.001556  0.001923  0.008789 -0.001373 -0.022461 -0.014252   
2 -0.040894 -0.013794  0.000824 -0.001312 -0.007385 -0.026337 -0.019623   
3 -0.035797 -0.019562 -0.001373 -0.009521 -0.012177 -0.025177 -0.021454   
4 -0.016754 -0.016754 -0.002289 -0.013824 -0.013428 -0.017181 -0.023438   

        Ch8       Ch9      Ch10      Ch11      Ch12      Ch13      Ch14  \
0  0.007385  0.028473  0.014343 -0.011627  0.026428 -0.054321  0.002380   
1 -0.012848  0.011444  0.004639 -0.051422  0.018250 -0.042572 -0.002655   
2 -0.025360 -0.007050 -0.004150 -0.063721  0.008698 -0.024017 -0.001312   
3 -0.026672 -0.021271 -0.011200 -0.044586  0.001007 -0.008667  0.004303   
4 -0.021057 -0.025085 -0.012665 -0.006775 -0.001923  0.002808  0.013123   

       Ch15      Ch16  
0 -0.051605 -0.016602  
1 -0.041779 -0.013275  
2 -0.013458 -0.013672  
3  0.015198 -0.012299  
4  0.033539  0.000000

## Import Timestamps

In [11]:
time = scipy.io.loadmat('data/data/sample_times.mat')
t = time['t']
m = np.min(t)
t = t - m #center around zero

#### Add to DataFrame.

In [12]:
potential_df['Time'] = np.transpose(t)

In [13]:
potential_df.head()

Ch1       Ch2       Ch3       Ch4       Ch5       Ch6       Ch7  \
0 -0.010132  0.010773  0.001038  0.018311  0.004303 -0.013550 -0.001831   
1 -0.030060 -0.001556  0.001923  0.008789 -0.001373 -0.022461 -0.014252   
2 -0.040894 -0.013794  0.000824 -0.001312 -0.007385 -0.026337 -0.019623   
3 -0.035797 -0.019562 -0.001373 -0.009521 -0.012177 -0.025177 -0.021454   
4 -0.016754 -0.016754 -0.002289 -0.013824 -0.013428 -0.017181 -0.023438   

        Ch8       Ch9      Ch10      Ch11      Ch12      Ch13      Ch14  \
0  0.007385  0.028473  0.014343 -0.011627  0.026428 -0.054321  0.002380   
1 -0.012848  0.011444  0.004639 -0.051422  0.018250 -0.042572 -0.002655   
2 -0.025360 -0.007050 -0.004150 -0.063721  0.008698 -0.024017 -0.001312   
3 -0.026672 -0.021271 -0.011200 -0.044586  0.001007 -0.008667  0.004303   
4 -0.021057 -0.025085 -0.012665 -0.006775 -0.001923  0.002808  0.013123   

       Ch15      Ch16        Time  
0 -0.051605 -0.016602    0.000000  
1 -0.041779 -0.013275   30.719736  
2 -0.013458 -0.013672   61.439472  
3  0.015198 -0.012299   92.159209  
4  0.033539  0.000000  122.878945

## Import Event Time Data

#### Import data showing the time when the stimulus switched between stimuli.

In [15]:
events = scipy.io.loadmat('data/data/events.mat')
events = events['events']

#### Should be a 2 column array. The first column is the timestamp of the event - what we care about.

In [16]:
event_time = events[:, 0]
event_time

array([5.21625882e+09, 5.22613815e+09, 5.23034674e+09, ...,
       8.83492420e+09, 8.87643482e+09, 8.87749398e+09])

In [17]:
# center around start of sample times
event_time = event_time - m
event_time

array([-1.42840000e+04,  9.86504800e+06,  1.40736310e+07, ...,
        3.61865110e+09,  3.66016172e+09,  3.66122088e+09])

## Align Event & Recording Data

#### Find the sample times that are closest to event times. Discard the first 3 and the last 2. Then, take every 6 times. These align with the events where the stimuli switch.

In [18]:
inds = event_time // np.mean(np.diff(t))
inds

array([-4.65000000e+02,  3.21130000e+05,  4.58129000e+05, ...,
        1.17795643e+08,  1.19146911e+08,  1.19181390e+08])

In [19]:
inds = inds[2:len(inds) - 2]
inds = inds[0:len(inds):6]

In [20]:
inds.shape

(1201,)

In [21]:
(np.diff(inds))/32556 #each stimulus should be 3 seconds

array([2.99972355, 2.99969284, 2.99972355, ..., 2.99972355, 2.99972355,
       2.99972355])

## Extract and Save Data Trials

#### Separate by stimulus (every other trial) and save the portion of the Pandas array corresponding to the samples in that trial. Each file will contain 17 columns (16 channels, and 1 for time) and a row for each sample (will vary slightly by trial but ~97000).

In [25]:
## save as h5

# import h5py

stim = 'A' #initially

for i in range(0, 1201): 
    print('Creating file ' + str(i+1) + ' of ' + str(1200) + '...')

    path = 'data/data/Stimulus_' + stim
    filename = 'stim_' + stim + '_' + str(i) + '.csv'
#     f = h5py.File(path + '/' + filename, 'w')
#     f.create_dataset('dataset_1', potential_df[int(inds[i]):int(inds[i+1])])
#     f.close()

    np.savetxt(path + '/' + filename, potential_df[int(inds[i]):int(inds[i+1])], delimiter=',')

    if stim is 'A':
        stim = 'B'
    else: 
        stim = 'A'

Creating file 1 of 1200...
Creating file 2 of 1200...
Creating file 3 of 1200...
Creating file 4 of 1200...
Creating file 5 of 1200...
Creating file 6 of 1200...
Creating file 7 of 1200...
Creating file 8 of 1200...
Creating file 9 of 1200...
Creating file 10 of 1200...
Creating file 11 of 1200...
Creating file 12 of 1200...
Creating file 13 of 1200...
Creating file 14 of 1200...
Creating file 15 of 1200...
Creating file 16 of 1200...
Creating file 17 of 1200...
Creating file 18 of 1200...
Creating file 19 of 1200...
Creating file 20 of 1200...
Creating file 21 of 1200...
Creating file 22 of 1200...
Creating file 23 of 1200...
Creating file 24 of 1200...
Creating file 25 of 1200...
Creating file 26 of 1200...
Creating file 27 of 1200...
Creating file 28 of 1200...
Creating file 29 of 1200...
Creating file 30 of 1200...
Creating file 31 of 1200...
Creating file 32 of 1200...
Creating file 33 of 1200...
Creating file 34 of 1200...
Creating file 35 of 1200...
Creating file 36 of 1200...
C

Creating file 288 of 1200...
Creating file 289 of 1200...
Creating file 290 of 1200...
Creating file 291 of 1200...
Creating file 292 of 1200...
Creating file 293 of 1200...
Creating file 294 of 1200...
Creating file 295 of 1200...
Creating file 296 of 1200...
Creating file 297 of 1200...
Creating file 298 of 1200...
Creating file 299 of 1200...
Creating file 300 of 1200...
Creating file 301 of 1200...
Creating file 302 of 1200...
Creating file 303 of 1200...
Creating file 304 of 1200...
Creating file 305 of 1200...
Creating file 306 of 1200...
Creating file 307 of 1200...
Creating file 308 of 1200...
Creating file 309 of 1200...
Creating file 310 of 1200...
Creating file 311 of 1200...
Creating file 312 of 1200...
Creating file 313 of 1200...
Creating file 314 of 1200...
Creating file 315 of 1200...
Creating file 316 of 1200...
Creating file 317 of 1200...
Creating file 318 of 1200...
Creating file 319 of 1200...
Creating file 320 of 1200...
Creating file 321 of 1200...
Creating file 

Creating file 571 of 1200...
Creating file 572 of 1200...
Creating file 573 of 1200...
Creating file 574 of 1200...
Creating file 575 of 1200...
Creating file 576 of 1200...
Creating file 577 of 1200...
Creating file 578 of 1200...
Creating file 579 of 1200...
Creating file 580 of 1200...
Creating file 581 of 1200...
Creating file 582 of 1200...
Creating file 583 of 1200...
Creating file 584 of 1200...
Creating file 585 of 1200...
Creating file 586 of 1200...
Creating file 587 of 1200...
Creating file 588 of 1200...
Creating file 589 of 1200...
Creating file 590 of 1200...
Creating file 591 of 1200...
Creating file 592 of 1200...
Creating file 593 of 1200...
Creating file 594 of 1200...
Creating file 595 of 1200...
Creating file 596 of 1200...
Creating file 597 of 1200...
Creating file 598 of 1200...
Creating file 599 of 1200...
Creating file 600 of 1200...
Creating file 601 of 1200...
Creating file 602 of 1200...
Creating file 603 of 1200...
Creating file 604 of 1200...
Creating file 

Creating file 854 of 1200...
Creating file 855 of 1200...
Creating file 856 of 1200...
Creating file 857 of 1200...
Creating file 858 of 1200...
Creating file 859 of 1200...
Creating file 860 of 1200...
Creating file 861 of 1200...
Creating file 862 of 1200...
Creating file 863 of 1200...
Creating file 864 of 1200...
Creating file 865 of 1200...
Creating file 866 of 1200...
Creating file 867 of 1200...
Creating file 868 of 1200...
Creating file 869 of 1200...
Creating file 870 of 1200...
Creating file 871 of 1200...
Creating file 872 of 1200...
Creating file 873 of 1200...
Creating file 874 of 1200...
Creating file 875 of 1200...
Creating file 876 of 1200...
Creating file 877 of 1200...
Creating file 878 of 1200...
Creating file 879 of 1200...
Creating file 880 of 1200...
Creating file 881 of 1200...
Creating file 882 of 1200...
Creating file 883 of 1200...
Creating file 884 of 1200...
Creating file 885 of 1200...
Creating file 886 of 1200...
Creating file 887 of 1200...
Creating file 

Creating file 1132 of 1200...
Creating file 1133 of 1200...
Creating file 1134 of 1200...
Creating file 1135 of 1200...
Creating file 1136 of 1200...
Creating file 1137 of 1200...
Creating file 1138 of 1200...
Creating file 1139 of 1200...
Creating file 1140 of 1200...
Creating file 1141 of 1200...
Creating file 1142 of 1200...
Creating file 1143 of 1200...
Creating file 1144 of 1200...
Creating file 1145 of 1200...
Creating file 1146 of 1200...
Creating file 1147 of 1200...
Creating file 1148 of 1200...
Creating file 1149 of 1200...
Creating file 1150 of 1200...
Creating file 1151 of 1200...
Creating file 1152 of 1200...
Creating file 1153 of 1200...
Creating file 1154 of 1200...
Creating file 1155 of 1200...
Creating file 1156 of 1200...
Creating file 1157 of 1200...
Creating file 1158 of 1200...
Creating file 1159 of 1200...
Creating file 1160 of 1200...
Creating file 1161 of 1200...
Creating file 1162 of 1200...
Creating file 1163 of 1200...
Creating file 1164 of 1200...
Creating f

IndexError: index 1201 is out of bounds for axis 0 with size 1201